# Generated by Django 3.2 on 2021-04-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='path',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
